### ISSUE TITLE
配置文件vpnservice中26.26.26.1和26.26.26.2这样的地址是什么意思呢

### ISSUE THREAD

**Issue by hetykai** [xiaokangwang/AndroidLibV2ray#1]
原issue在这儿。 [https://github.com/RayFantasyStudio/V2Ray-Android/issues/10]

为了搞清楚移步到这儿了。可以说明一下吗，谢谢

**Comment by xiaokangwang** [comment]
如果您是非专业开发人员，您可以理解为是虚拟IP地址，您手机上的软件会认为您的IP地址是26.26.26.1。但实际上网站获取到您的IP是您的服务器的IP。 和WiFI网络下的192.168.1.1之类的IP类似。 

对于开发人员，26.26.26.1在VPN所在的interface上分配给您的设备的IP，26.26.26.2是网关IP，这些IP会被tun2socks用于转发网络流量。之所以选择这样一个不常见的IP是为了防止和目前已经有的IP地址冲突。

**Comment by ghost** [comment]
26.0.0.0/8 是分配给美国国防部的IP段（笑
