### ISSUE TITLE
the purpose of using unix.Connect and its FileConn?

### ISSUE THREAD

**Issue by rurirei** [xiaokangwang/AndroidLibV2ray#30]
hello, could you please say the purpose of specifying the unix socket to return the conn? i found the simply net.Dialer.Dial done this as well.

great thanks for this repo.

https://github.com/xiaokangwang/AndroidLibV2ray/blob/cfa1f0981fa509ad6c50f0c77c580465b2d21a06/VPN/vpnservice_support.go#L44-L62

```go
var dialer = &net.Dialer{
    // dialer simply get and protect the fd in addition
    Control: func(fd uintptr) { protect(fd) }
}

return dialer.DialContext(ctx, network, dest)
```

**Comment by rurirei** [comment]
@xiaokangwang @2dust @yuhan6665

**Comment by xiaokangwang** [comment]
> @xiaokangwang @2dust @yuhan6665

The important part is here

sDialer.vp.VpnSupportSet.Protect(fd)

This notify the android operating system that this connection should not be routed through the VPN. Otherwise, the connection from V2Ray to V2Ray server will enter the VPN, forming a loop.

**Comment by rurirei** [comment]
thanks for your reply.

what i wnat to know is if there is some advantages to create unix.Connect manually, comparing to net.dialer.Dial()?

**Comment by xiaokangwang** [comment]
> thanks for your reply.
> 
> what i wnat to know is if there is some advantages to create unix.Connect manually, comparing to net.dialer.Dial()?

When you dial, ordinarily you do not have the opportunity to `protect` it before `connect`. So, create it manually give you more control of what happens. The API to set option of the socket before connect is not present when this file is written.

**Comment by rurirei** [comment]
thanks.
